=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/schemas/InteractCarePath.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="care_path_xml">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element ref="steps" />
			</xs:sequence>
			<xs:attribute name="care_path_code" type="xs:string" />
			<xs:attribute name="care_path_name" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="next_care_path">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="step_flag" type="xs:boolean" 
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="care_path_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="step_id" type="xs:int"
					minOccurs="0" maxOccurs="1"/>	
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
	<xs:element name="symptom">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			  <xs:element ref="next_care_path" minOccurs="0" maxOccurs="unbounded" />	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="instruction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="detail_description" type="xs:string"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lab_result">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="vital_sign">
		<xs:complexType>
			<xs:sequence>
				<!-- Check if data is available for care_path_attr_code, tracked while recording Change In Condition,
				if not use value, datatype, min and max to validate -->
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="value" type="xs:string" />
				<xs:element name="datatype" type="xs:string" />
				<xs:element name="min" type="xs:string" />
				<xs:element name="max" type="xs:string" />
				<xs:element name="units" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lab_work">
		<xs:complexType>
			<xs:sequence>
				<!-- Check if data is available for care_path_attr_code, tracked while recording Change In Condition,
				if not use value, datatype, min and max to validate -->
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="0" />
				<xs:element name="value" type="xs:string" />
				<xs:element name="datatype" type="xs:string" />
				<xs:element name="min" type="xs:string" />
				<xs:element name="max" type="xs:string" />
				<xs:element name="units" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="met_any">
		<xs:complexType>
			<xs:choice>
				<xs:element name="next_step_id" type="xs:int"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="message" type="xs:string" minOccurs="0"
					maxOccurs="1" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="met_none">
		<xs:complexType>
			<xs:choice>
				<xs:element name="next_step_id" type="xs:int"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="message" type="xs:string" minOccurs="0"
					maxOccurs="1" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="decision">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="met_any" minOccurs="0" maxOccurs="1" />
				<xs:element ref="met_none" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="step">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="symptom" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="vital_sign" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="lab_work" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="lab_result" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="instruction" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="decision" />
			</xs:sequence> 
			<xs:attribute name="step_name" type="xs:string" />
			<xs:attribute name="step_id" type="xs:int" />
			<xs:attribute name="step_type" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="step" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/xml/Fever.xml
<?xml version="1.0" encoding="UTF-8"?>
<care_path_xml care_path_code="FV" care_path_name="FeVer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/InteractCarePath.xsd">
	<steps>
		<step step_name="Fever Definition" step_id="1">
			<symptom>
				<name>One temp > 100&#8457; ( > 37.8&#8451; )</name>
				<care_path_attr_code>CP_FV_S1_SYMPTOM1</care_path_attr_code>
			</symptom>
			<symptom>
				<name>Two temps > 99&#8457; ( > 37.2&#8451; ) oral or > 99.5&#8457; ( > 37.5&#8451;) rectal</name>
				<care_path_attr_code>CP_FV_S1_SYMPTOM2</care_path_attr_code>
			</symptom>
								
			<symptom>
				<name>Increase in temp of 2&#8457; ( 1.1&#8451; ) over baseline</name>
				<care_path_attr_code>CP_FV_S1_SYMPTOM3</care_path_attr_code>
				
			</symptom>		
			<decision>
				<met_any>
					<next_step_id>2</next_step_id>
				</met_any>
				<met_none>
					<message>DO_NOTHING</message>
				</met_none>
			</decision>	
		</step>
		<step step_name="Vital Sign Criteria" step_id="2">
			<vital_sign>
				<name>Temp</name>
				<care_path_attr_code>TEMP</care_path_attr_code>
				<value></value>
				<datatype>FLOAT</datatype>
				<min></min>
				<max>100.5</max>
				<units>Â°F</units>
			</vital_sign>
			<vital_sign>
				<name>Apical heart rate</name>
				<care_path_attr_code>APICAL_HEART_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>50</min>
				<max>100</max>
				<units></units>
			</vital_sign>	
			<vital_sign>
				<name>Respiratory rate</name>
				<care_path_attr_code>RESPIRATORY_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>10</min>
				<max>28</max>	
				<units>/min</units>				
			</vital_sign>
			<vital_sign>
				<name>Systolic BP</name>
				<care_path_attr_code>SYSTOLIC_BP</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max>200</max>
				<units></units>	
			</vital_sign>			
			<vital_sign>
				<name>Oxygen saturation</name>
				<care_path_attr_code>OXYGEN_SATURATION</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max></max>
				<units>%</units>	
			</vital_sign>	
			<vital_sign>
				<name>Finger stick glucose</name>
				<care_path_attr_code>FINGER_STICK_GLUCOSE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>70</min>
				<max>300</max>
				<units></units>	
			</vital_sign>			
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>3</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Evaluate Symptoms and Signs" step_id="3">
			<symptom>
				<name>Acute mental status change</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM1</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Not eating or drinking</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM2</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Acute decline in ADL abilities</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM3</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>New cough, abnormal lung sounds</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM4</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Nausea, vomiting, diarrhea</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM5</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>	
			<symptom>
				<name>Abdominal distension or tenderness</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM6</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>	
			<symptom>
				<name>New or worsened incontinence,pain with urination, blood in urine</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM7</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Very low urinary output</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM8</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			
			<symptom>
				<name>New skin condition (e.g. rash, redness suggesting cellulitis, signs of infection around existing wound or pressure ulcer)</name>
				<care_path_attr_code>CP_FV_S3_SYMPTOM9</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>AMSC</care_path_code>
				</next_care_path>
			</symptom>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>4</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Consider Orders for" step_id="4" step_type="CONSIDER_ORDERS">
			<instruction>
				<name>Portable chest X-ray</name>
				<care_path_attr_code>XRAY_PORTABLE_CHEST</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Urinalysis and C&amp;S if indicated</name>
				<care_path_attr_code>URINALYSIS_AND_CP_IF_INDICATED</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Blood work (Complete Blood Count, Basic Metabolic Panel )</name>
				<care_path_attr_code>BLOOD_WORK_CBC_BMP</care_path_attr_code>
			</instruction>	
			<decision>
				<met_any>
					<next_step_id>5</next_step_id>
				</met_any>
				<met_none>
					<next_step_id>5</next_step_id>
				</met_none>
			</decision>				
		</step>
		<step step_name="Evaluate Results" step_id="5">
			<lab_work>
				<name>WBC</name>
				<care_path_attr_code>WBC_COUNT</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min></min>
				<max>14000</max>
				<units></units>
			</lab_work>
			<lab_work> 
				<name>Neutrophils</name>
				<care_path_attr_code>CP_FV_S5_LAB_WORK1</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min></min>
				<max>90</max>
				<units>%</units>
			</lab_work>			
			<lab_result>
				<name>Infiltrate or pneumonia on chest X-ray</name>
				<care_path_attr_code>XRAY_PORTABLE_CHEST_ATTR1</care_path_attr_code>
			</lab_result>
			<lab_result>
				<name>Urine results suggest infection and symptoms or signs present</name>
				<care_path_attr_code>URINALYSIS_AND_CP_IF_INDICATED_ATTR1</care_path_attr_code>				
			</lab_result>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>6</next_step_id>
				</met_none>
			</decision>	
		</step>			
		<step step_name="Manage in Facility" step_id="6" step_type="MANAGE_IN_FACILITY">
			<symptom>
				<name>Worsening condition</name>
				<care_path_attr_code>CP_FV_S6_SYMPTOM1</care_path_attr_code>
			</symptom>
			<instruction>
				<name>Monitor vital signs, fluid intake/urine output every 4-8 hrs for 24-72 hrs</name>
				<detail_description>Temp &gt; 100.5&#8457;</detail_description>
				<detail_description>Apical heart rate &gt; 100 or &lt; 50</detail_description>
				<detail_description>Respiratory rate &gt; 28/min or &lt; 10/min</detail_description>
				<detail_description>BP &lt; 90 or &gt; 200 systolic</detail_description>
				<detail_description>Oxygen saturation &lt; 90%</detail_description>
				<detail_description>Finger stick glucose &lt; 70 or &gt; 300</detail_description>
				<care_path_attr_code>CP_FV_S6_INSTRUCTION1</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Do Not give acetaminophen unless necessary for comfort(it can mask fever), or until source of fever known</name>
				<care_path_attr_code>CP_FV_S6_INSTRUCTION2</care_path_attr_code>
			</instruction>
			<instruction>
				<name>If on diuretic, consider holding</name>
				<care_path_attr_code>CP_FV_S6_INSTRUCTION3</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Oral,IV or subcutaneous fluids if needed for hydration</name>
				<care_path_attr_code>CP_FV_S6_INSTRUCTION4</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Update advance care plan and directives if appropriate</name>
				<care_path_attr_code>CP_FV_S6_INSTRUCTION5</care_path_attr_code>
			</instruction>
			
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<message>Monitor vital signs, fluid intake/urine output every 4-8 hrs for 24-72 hrs</message>
				</met_none>
			</decision>	
		</step>		
	</steps>
</care_path_xml>

=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/xml/LowerRespiratoryInfection.xml
<?xml version="1.0" encoding="UTF-8"?>
<care_path_xml care_path_code="LRI" care_path_name="Lower Respiratory Infection" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/InteractCarePath.xsd">
	<steps>
		<step step_name="Symptoms or Lower RespiratoryInfection Noted" step_id="1">
			<symptom>
				<name>New or worsened cough</name>
				<care_path_attr_code>CP_LRI_S1_SYMPTOM1</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>New or increased sputum production</name>
				<care_path_attr_code>CP_LRI_S1_SYMPTOM2</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>New or worsening shortness of breath</name>
				<care_path_attr_code>CP_LRI_S1_SYMPTOM3</care_path_attr_code>
				
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>SOB</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Chest pain with inspiration or coughing</name>
				<care_path_attr_code>CP_LRI_S1_SYMPTOM4</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>New or increased findings on lung exam (rales, wheezes)</name>
				<care_path_attr_code>CP_LRI_S1_SYMPTOM5</care_path_attr_code>
				
			</symptom>	
			<decision>
				<met_any>
					<next_step_id>2</next_step_id>
				</met_any>
				<met_none>
					<message>DO_NOTHING</message>
				</met_none>
			</decision>	
		</step>
		<step step_name="Vital Sign Criteria" step_id="2">
			  <symptom>
				<name>Resident unable to eat or drink</name>
				<care_path_attr_code>CP_LRI_S2_SYMPTOM1</care_path_attr_code>
            </symptom>
			<vital_sign>
				<name>Temp</name>
				<care_path_attr_code>TEMP</care_path_attr_code>
				<value></value>
				<datatype>FLOAT</datatype>
				<min></min>
				<max>100.5</max>
				<units>Â°F</units>
			</vital_sign>
			<vital_sign>
				<name>Apical heart rate</name>
				<care_path_attr_code>APICAL_HEART_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>50</min>
				<max>100</max>
				<units></units>
			</vital_sign>	
			<vital_sign>
				<name>Respiratory rate</name>
				<care_path_attr_code>RESPIRATORY_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>10</min>
				<max>28</max>	
				<units>/min</units>				
			</vital_sign>
			<vital_sign>
				<name>Systolic BP</name>
				<care_path_attr_code>SYSTOLIC_BP</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max>200</max>
				<units></units>	
			</vital_sign>			
			<vital_sign>
				<name>Oxygen saturation</name>
				<care_path_attr_code>OXYGEN_SATURATION</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max></max>
				<units>%</units>	
			</vital_sign>	
			<vital_sign>
				<name>Finger stick glucose</name>
				<care_path_attr_code>FINGER_STICK_GLUCOSE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>70</min>
				<max>300</max>
				<units></units>	
			</vital_sign>
          				
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>3</next_step_id>
				</met_none>
			</decision>	
		</step>		
		
		<step step_name="Consider Orders for" step_id="3" step_type="CONSIDER_ORDERS">
			<instruction>
				<name>Portable chest X-ray</name>
				<care_path_attr_code>XRAY_PORTABLE_CHEST</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Blood work (Complete Blood Count, Basic Metabolic Panel )</name>
				<care_path_attr_code>BLOOD_WORK_CBC_BMP</care_path_attr_code>
			</instruction>	
			<decision>
				<met_any>
					<next_step_id>4</next_step_id>
				</met_any>
				<met_none>
					<next_step_id>4</next_step_id>
				</met_none>
			</decision>				
		</step>
		<step step_name="Evaluate Results" step_id="4">
		<lab_result>
				<name>Infiltrate or pneumonia on chest X-ray</name>
				<care_path_attr_code>XRAY_PORTABLE_CHEST_ATTR1</care_path_attr_code>
			</lab_result>
			<lab_result>
				<name>Critical values in blood count or metabolic panel</name>
				<care_path_attr_code>BLOOD_WORK_WITH_MORE_DETAILS_ATTR2</care_path_attr_code>				
			</lab_result>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>5</next_step_id>
				</met_none>
			</decision>	
		</step>			
		<step step_name="Manage in Facility" step_id="5" step_type="MANAGE_IN_FACILITY">
			<symptom>
				<name>Worsening condition</name>
				<care_path_attr_code>CP_LRI_S6_SYMPTOM1</care_path_attr_code>
			</symptom>
			<instruction>
				<name>Monitor vital signs, fluid intake/urine output every 4-8 hrs </name>
				<detail_description>Temp &gt; 100.5&#8457;</detail_description>
				<detail_description>Apical heart rate &gt; 100 or &lt; 50</detail_description>
				<detail_description>Respiratory rate &gt; 28/min or &lt; 10/min</detail_description>
				<detail_description>BP &lt; 90 or &gt; 200 systolic</detail_description>
				<detail_description>Oxygen saturation &lt; 90%</detail_description>
				<detail_description>Finger stick glucose &lt; 70 or &gt; 300</detail_description>
				<care_path_attr_code>CP_CIB_S6_INSTRUCTION1</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Oral, IV or subcutaneous fluids if needed for hydration</name>
				<care_path_attr_code>CP_LRI_S5_INSTRUCTION2</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Oxygen supplementation as indicated</name>
				<care_path_attr_code>CP_LRI_S5_INSTRUCTION3</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Nebulizer treatments and/or cough suppressants as indicated</name>
				<care_path_attr_code>CP_LRI_S5_INSTRUCTION4</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Consider antibiotic therapy (check allergies)</name>
				<care_path_attr_code>CP_LRI_S5_INSTRUCTION5</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Update advance care plan and directives if appropriate</name>
				<care_path_attr_code>CP_LRI_S5_INSTRUCTION6</care_path_attr_code>
			</instruction>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<message>Monitor vital signs, fluid intake/urine output every 4-8 hrs for 24-72 hrs</message>
				</met_none>
			</decision>	
		</step>		
	</steps>
</care_path_xml>

=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/xml/ShortnesOfBreath.xml
<?xml version="1.0" encoding="UTF-8"?>
<care_path_xml care_path_code="SOB" care_path_name="Shortness of Breath" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/InteractCarePath.xsd">
	<steps>
		<step step_name="Symptoms of Shortness of Breath" step_id="1">
			<symptom>
				<name>Difficult or labored breathing that is out of proportion to the resident’s level of physical activity</name>
				<care_path_attr_code>CP_SOB_S1_SYMPTOM1</care_path_attr_code>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>CHF</care_path_code>
				</next_care_path>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>LRI</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>New complaint of SOB</name>
				<care_path_attr_code>CP_SOB_S1_SYMPTOM2</care_path_attr_code>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>CHF</care_path_code>
				</next_care_path>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>LRI</care_path_code>
				</next_care_path>				
			</symptom>
									
			<decision>
				<met_any>
					<next_step_id>2</next_step_id>
				</met_any>
				<met_none>
					<message>DO_NOTHING</message>
				</met_none>
			</decision>	
		</step>
		<step step_name="Vital Sign Criteria" step_id="2">
			<symptom>
				<name>Accessory breathing muscle use</name>
				<care_path_attr_code>CP_SOB_S2_SYMPTOM1</care_path_attr_code>
            </symptom>
             <symptom>
				<name>Cyanosis</name>
				<care_path_attr_code>CP_SOB_S2_SYMPTOM2</care_path_attr_code>	
             </symptom>
             <symptom>
				<name>New or worsening chest pains</name>
				<care_path_attr_code>CP_SOB_S2_SYMPTOM3</care_path_attr_code>
			</symptom>
			<vital_sign>
				<name>Temp</name>
				<care_path_attr_code>TEMP</care_path_attr_code>
				<value></value>
				<datatype>FLOAT</datatype>
				<min></min>
				<max>100.5</max>
				<units>°F</units>
			</vital_sign>
			<vital_sign>
				<name>Apical heart rate</name>
				<care_path_attr_code>APICAL_HEART_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>50</min>
				<max>100</max>
				<units></units>
			</vital_sign>	
			<vital_sign>
				<name>Respiratory rate</name>
				<care_path_attr_code>RESPIRATORY_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>10</min>
				<max>28</max>	
				<units>/min</units>				
			</vital_sign>
			<vital_sign>
				<name>Systolic BP</name>
				<care_path_attr_code>SYSTOLIC_BP</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max>200</max>
				<units></units>	
			</vital_sign>			
			<vital_sign>
				<name>Oxygen saturation</name>
				<care_path_attr_code>OXYGEN_SATURATION</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max></max>
				<units>%</units>	
			</vital_sign>	
			<vital_sign>
				<name>Finger stick glucose</name>
				<care_path_attr_code>FINGER_STICK_GLUCOSE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>70</min>
				<max>300</max>
				<units></units>	
			</vital_sign>
             			 
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>3</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Further Nursing Evaluation" step_id="3">
			<symptom>
				<name>Cough with or without sputum production</name>
				<care_path_attr_code>CP_SOB_S3_SYMPTOM1</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Abnormal breathing sounds (wheezing, rales, rhonchi, etc…)</name>
				<care_path_attr_code>CP_SOB_S3_SYMPTOM2</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Edema</name>
				<care_path_attr_code>CP_SOB_S3_SYMPTOM3</care_path_attr_code>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>CHF</care_path_code>
				</next_care_path>
				<next_care_path>
					<step_flag>false</step_flag>
					<care_path_code>LRI</care_path_code>
				</next_care_path>
			</symptom>
			<symptom>
				<name>Change in mental status</name>
				<care_path_attr_code>CP_SOB_S3_SYMPTOM4</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Inability to eat or sleep due to SOB</name>
				<care_path_attr_code>CP_SOB_S3_SYMPTOM5</care_path_attr_code>
				
			</symptom>	
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>4</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Consider Orders for" step_id="4" step_type="CONSIDER_ORDERS">
			<instruction>
				<name>Portable chest X-ray</name>
				<care_path_attr_code>XRAY_PORTABLE_CHEST</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Blood work (Complete Blood Count, Basic Metabolic Panel )</name>
				<care_path_attr_code>BLOOD_WORK_CBC_BMP</care_path_attr_code>
			</instruction>
			<instruction>
				<name>EKG (if available)</name>
				<care_path_attr_code>EKG</care_path_attr_code>
			</instruction>
            <instruction>
				<name>Bedside spirometry (if available and no cognitive impairment)</name>
				<care_path_attr_code>BEDSIDE_SPIROMETRY</care_path_attr_code>
			</instruction>			
			<decision>
				<met_any>
					<next_step_id>5</next_step_id>
				</met_any>
				<met_none>
					<next_step_id>5</next_step_id>
				</met_none>
			</decision>				
		</step>
		<step step_name="Evaluate Results" step_id="5">
			<lab_work>
				<name>WBC</name>
				<care_path_attr_code>WBC_COUNT</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min></min>
				<max>14000</max>
				<units></units>
			</lab_work>
			<lab_result>
				<name>Abnormal CXR suggestive of CHF, COPD, pneumonia, atelectasis,lung CA or pleural effusion</name>
				<care_path_attr_code>BLOOD_WORK_CBC_BMP_ATTR2</care_path_attr_code>
				
			</lab_result>		
			<lab_result>
				<name>Critical values in blood count or metabolic panel</name>
				<care_path_attr_code>BLOOD_WORK_CBC_BMP_ATTR1</care_path_attr_code>
			</lab_result>
			<lab_result>
				<name>EKG shows new changes suggestive of MI or arrhythmia</name>
				<care_path_attr_code>EKG_ATTR1</care_path_attr_code>				
			</lab_result>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>6</next_step_id>
				</met_none>
			</decision>	
		</step>			
		<step step_name="Manage in Facility" step_id="6" step_type="MANAGE_IN_FACILITY">
			<symptom>
				<name>Worsening condition</name>
				<care_path_attr_code>CP_SOB_S6_SYMPTOM1</care_path_attr_code>
			</symptom>
			<instruction>
				<name>Monitor vital signs, fluid intake/urine output every 4-8 hrs</name>
				<detail_description>Temp &gt; 100.5&#8457;</detail_description>
				<detail_description>Apical heart rate &gt; 100 or &lt; 50</detail_description>
				<detail_description>Respiratory rate &gt; 28/min or &lt; 10/min</detail_description>
				<detail_description>BP &lt; 90 or &gt; 200 systolic</detail_description>
				<detail_description>Oxygen saturation &lt; 90%</detail_description>
				<detail_description>Finger stick glucose &lt; 70 or &gt; 300</detail_description>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION1</care_path_attr_code>
			</instruction>
			<instruction>
				<name>O2 supplementation as indicated</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION2</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Consider initiating or modifying dose of medications (e.g. diuretics,teroids, nebulizers, etc…)</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION3</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Respiratory therapy (if available)</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION4</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Ensure influenza and pneumococcal immunizations are up to date</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION5</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Encourage smoking cessation (if applicable)</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION6</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Update advance care plan and directives if appropriate</name>
				<care_path_attr_code>CP_SOB_S6_INSTRUCTION7</care_path_attr_code>
			</instruction>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<message>Monitor vital signs, fluid intake/urine output every 4-8 hrs for 24-72 hrs</message>
				</met_none>
			</decision>	
		</step>		
	</steps>
</care_path_xml>
