=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/schemas/InteractCarePath.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="care_path_xml">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element ref="steps" />
			</xs:sequence>
			<xs:attribute name="care_path_code" type="xs:string" />
			<xs:attribute name="care_path_name" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="next_care_path">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="step_flag" type="xs:boolean" 
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="care_path_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="step_id" type="xs:int"
					minOccurs="0" maxOccurs="1"/>	
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
	<xs:element name="symptom">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			  <xs:element ref="next_care_path" minOccurs="0" maxOccurs="unbounded" />	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="instruction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="detail_description" type="xs:string"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lab_result">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="vital_sign">
		<xs:complexType>
			<xs:sequence>
				<!-- Check if data is available for care_path_attr_code, tracked while recording Change In Condition,
				if not use value, datatype, min and max to validate -->
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="1" maxOccurs="1"/>
				<xs:element name="value" type="xs:string" />
				<xs:element name="datatype" type="xs:string" />
				<xs:element name="min" type="xs:string" />
				<xs:element name="max" type="xs:string" />
				<xs:element name="units" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lab_work">
		<xs:complexType>
			<xs:sequence>
				<!-- Check if data is available for care_path_attr_code, tracked while recording Change In Condition,
				if not use value, datatype, min and max to validate -->
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="care_path_attr_code" type="xs:string"
					minOccurs="0" />
				<xs:element name="value" type="xs:string" />
				<xs:element name="datatype" type="xs:string" />
				<xs:element name="min" type="xs:string" />
				<xs:element name="max" type="xs:string" />
				<xs:element name="units" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="met_any">
		<xs:complexType>
			<xs:choice>
				<xs:element name="next_step_id" type="xs:int"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="message" type="xs:string" minOccurs="0"
					maxOccurs="1" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="met_none">
		<xs:complexType>
			<xs:choice>
				<xs:element name="next_step_id" type="xs:int"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="message" type="xs:string" minOccurs="0"
					maxOccurs="1" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="decision">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="met_any" minOccurs="0" maxOccurs="1" />
				<xs:element ref="met_none" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="step">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="symptom" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="vital_sign" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="lab_work" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="lab_result" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="instruction" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="decision" />
			</xs:sequence> 
			<xs:attribute name="step_name" type="xs:string" />
			<xs:attribute name="step_id" type="xs:int" />
			<xs:attribute name="step_type" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="step" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Dejiva/Carecent/interact.parent/interact.core/src/main/carepath/xml/Gastrointestinal(GI)Symptoms.xml
<?xml version="1.0" encoding="UTF-8"?>
<care_path_xml care_path_code="GI" care_path_name="Gastrointestinal(GI)Symptoms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/InteractCarePath.xsd">
	<steps>
		<step step_name="New or Worsening GI Symptoms or Signs" step_id="1">
			<symptom>
				<name>Nausea and/or vomiting</name>
				<care_path_attr_code>CP_GI_S1_SYMPTOM1</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Diarrhea (3 or more loose or liquid bowel movements per day)</name>
				<care_path_attr_code>CP_GI_S1_SYMPTOM2</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Constipation(no bowel movement in 3 days)</name>
				<care_path_attr_code>CP_GI_S1_SYMPTOM3</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Abdominal pain</name>
				<care_path_attr_code>CP_GI_S1_SYMPTOM4</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Distended abdomen</name>
				<care_path_attr_code>CP_GI_S1_SYMPTOM5</care_path_attr_code>
				
			</symptom>	
				
			<decision>
				<met_any>
					<next_step_id>2</next_step_id>
				</met_any>
				<met_none>
					<message>DO_NOTHING</message>
				</met_none>
			</decision>	
		</step>
		<step step_name="Vital Sign Criteria" step_id="2">
			<vital_sign>
				<name>Temp</name>
				<care_path_attr_code>TEMP</care_path_attr_code>
				<value></value>
				<datatype>FLOAT</datatype>
				<min></min>
				<max>100.5</max>
				<units>Â°F</units>
			</vital_sign>
			<vital_sign>
				<name>Apical heart rate</name>
				<care_path_attr_code>APICAL_HEART_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>50</min>
				<max>100</max>
				<units></units>
			</vital_sign>	
			<vital_sign>
				<name>Respiratory rate</name>
				<care_path_attr_code>RESPIRATORY_RATE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>10</min>
				<max>28</max>	
				<units>/min</units>				
			</vital_sign>
			<vital_sign>
				<name>Systolic BP</name>
				<care_path_attr_code>SYSTOLIC_BP</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max>200</max>
				<units></units>	
			</vital_sign>			
			<vital_sign>
				<name>Oxygen saturation</name>
				<care_path_attr_code>OXYGEN_SATURATION</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>90</min>
				<max></max>
				<units>%</units>	
			</vital_sign>	
			<vital_sign>
				<name>Finger stick glucose</name>
				<care_path_attr_code>FINGER_STICK_GLUCOSE</care_path_attr_code>
				<value></value>
				<datatype>INT</datatype>
				<min>70</min>
				<max>300</max>
				<units></units>	
			</vital_sign>			
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>3</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Further Nursing Evaluation" step_id="3">
			<symptom>
				<name>Abdominal tenderness or distention</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM1</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Absent or hyperactive bowel sounds</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM2</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Jaundice</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM3</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Blood in stool or vomitus</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM4</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Recurrent diarrhea after treatment for C. difficile</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM5</care_path_attr_code>
				
			</symptom>	
			<symptom>
				<name>Other residents with similar symptoms suggesting outbreak of a GI virus</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM6</care_path_attr_code>
				
			</symptom>	
			<symptom>
				<name>Recent initiation or adjustment of enteral tube feeding (diarrhea)</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM7</care_path_attr_code>
				
			</symptom>
			<symptom>
				<name>Recent initiation or adjustment of narcotic medication (constipation)</name>
				<care_path_attr_code>CP_GI_S3_SYMPTOM8</care_path_attr_code>
				
			</symptom>
			
			
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>4</next_step_id>
				</met_none>
			</decision>	
		</step>		
		<step step_name="Consider Orders for" step_id="4" step_type="CONSIDER_ORDERS">
			<instruction>
				<name>Abdominal X-ray or ultrasound (if available)</name>
				<care_path_attr_code>XRAY_OR_ULTRASOUND_ABDOMINAL_IF_AVAILABLE</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Stool specimen for occult blood</name>
				<care_path_attr_code>STOOL_SPECIMER_FOR_OCCULT_BLOOD</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Stool specimen for culture and C. difficile toxin assay</name>
				<care_path_attr_code>STOOL_SPECIMER_FOR_CULTURE_AND_TOXIN</care_path_attr_code>
			</instruction>
            <instruction>
				<name>Blood work</name>
				<detail_description>CBC, comprehensive metabolic panel (including liver function tests)</detail_description>
				<detail_description>Amylase, lipase, thyroid function</detail_description>
				<detail_description>Digoxin blood level (if relevant,for nausea/vomiting)</detail_description>
				<care_path_attr_code>BLOOD_WORK_WITH_MORE_DETAILS</care_path_attr_code>
			</instruction>			
			<decision>
				<met_any>
					<next_step_id>5</next_step_id>
				</met_any>
				<met_none>
					<next_step_id>5</next_step_id>
				</met_none>
			</decision>				
		</step>
		<step step_name="Evaluate Results" step_id="5">
			
			<lab_result>
				<name>Results of abdominal X-ray/ultrasound suggests ileus,obstruction, mass, or perforation</name>
				<care_path_attr_code>XRAY_OR_ULTRASOUND_ABDOMINAL_IF_AVAILABLE_ATTR1</care_path_attr_code>
			</lab_result>
			<lab_result>
				<name>Critical values in blood work</name>
				<care_path_attr_code>BLOOD_WORK_WITH_MORE_DETAILS_ATTR1</care_path_attr_code>				
			</lab_result>
			<lab_result>
				<name>Stool analysis suggests infection</name>
				<care_path_attr_code>STOOL_SPECIMER_FOR_OCCULT_BLOOD_ATTR1</care_path_attr_code>				
			</lab_result>
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<next_step_id>6</next_step_id>
				</met_none>
			</decision>	
		</step>			
		<step step_name="Manage in Facility" step_id="6" step_type="MANAGE_IN_FACILITY">
			<symptom>
				<name>Worsening condition</name>
				<care_path_attr_code>CP_GI_S6_SYMPTOM1</care_path_attr_code>
			</symptom>
			<instruction>
				<name>Monitor vital signs, fluid intake/urine output every 4-8 hrs</name>
				<detail_description>Temp &gt; 100.5&#8457;</detail_description>
				<detail_description>Apical heart rate &gt; 100 or &lt; 50</detail_description>
				<detail_description>Respiratory rate &gt; 28/min or &lt; 10/min</detail_description>
				<detail_description>BP &lt; 90 or &gt; 200 systolic</detail_description>
				<detail_description>Oxygen saturation &lt; 90%</detail_description>
				<detail_description>Finger stick glucose &lt; 70 or &gt; 300</detail_description>
				<care_path_attr_code>CP_GI_S6_INSTRUCTION1</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Monitor intake and urine output(and number of episodes for vomiting and diarrhea)</name>
				<care_path_attr_code>CP_GI_S6_INSTRUCTION2</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Initiate medications for nausea, vomiting, diarrhea,constipation as appropriate</name>
				<care_path_attr_code>CP_GI_S6_INSTRUCTION3</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Consider IV or subcutaneous fluids if needed for hydration</name>
				<care_path_attr_code>CP_GI_S6_INSTRUCTION4</care_path_attr_code>
			</instruction>
			<instruction>
				<name>Update advance care plan and directives if appropriate</name>
				<care_path_attr_code>CP_GI_S6_INSTRUCTION5</care_path_attr_code>
			</instruction>
			
			<decision>
				<met_any>
					<message>NOTIFY_MD_NP_PA</message>
				</met_any>
				<met_none>
					<message>Monitor vital signs, fluid intake/urine output every 4-8 hrs for 24-72 hrs</message>
				</met_none>
			</decision>	
		</step>		
	</steps>
</care_path_xml>
